version: '3'
services:
  shastic_challenge:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - mysql
    volumes:
      - ./:/app
    stdin_open: true
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: ''
